<html>
  <head>
    <base href="/">
    <title>DateBuilder</title>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="styles.css">
    <!-- 1. Load libraries -->
     <!-- Polyfill(s) for older browsers -->
    <script src="node_modules/core-js/client/shim.min.js"></script>
    <script src="node_modules/zone.js/dist/zone.js"></script>
    <script src="node_modules/reflect-metadata/Reflect.js"></script>
    <script src="node_modules/systemjs/dist/system.src.js"></script>
    <!-- 2. Configure SystemJS -->
    <script src="systemjs.config.js"></script>
    <script>
      System.import('app').catch(function(err){ console.error(err); });
    </script>
    
    <script src="node_modules/jquery/dist/jquery.min.js"></script>
    <script src="https://www.atlasestateagents.co.uk/javascript/tether.min.js"></script><!-- Tether for Bootstrap --> 
    
    <link rel="stylesheet" type="html/css" href="node_modules/bootstrap/dist/css/bootstrap.min.css">
    <script src="node_modules/bootstrap/dist/js/bootstrap.min.js"></script>

    <link rel="stylesheet" type="html/css" href="node_modules/bootstrap-material-design/dist/css/bootstrap-material-design.min.css">
    <script src="node_modules/bootstrap-material-design/dist/js/material.min.js"></script>
    <script>
      $(document).ready(function(){
        $.material.init();
      })
    </script>
    <style>
    *{
      font-family: 'Roboto', 'Helvetica', 'Arial', sans-serif;
      font-weight: 300;
    }   
    </style>
  </head>
  <!-- 3. Display the application -->
  <body>
    <div class="container">
      <my-app>Loading...</my-app>
    </div>
  </body>
</html>